### ISSUE TITLE
Renaming Crank?

### ISSUE THREAD

**Issue by palavrov** [bikeshaving/crank#112]
Naming is hard and 'crank' is really cool but what about combining JS + JSX in JS/X (or JS!X, JS@X, JS#X, J$X, JS%X, JS^X, JS&X, JS*X, JS+X, JS=X, JS~X, JS|X?

**Comment by brainkim** [comment]
Hmmm are you saying that we should change the name of library? I’m open to suggestions, but I really like Crank, mainly because I think there is a way to write idiomatic code in Crank that is different from writing code in, for instance, React, and I’ve started to call code which is idiomatic to Crank, “cranky” which tickles me, I dunno.

“To crank” something is also to apply a circular motion to a gear or pedal, and I think it’s a descriptive name for what it feels like to write components with generators. Each generator is its own internal loop, or gear, and these gears are connected in concentric fashion between parent and child by the parent/child relationship between virtual elements.

RE: why not a name based on JSX, I love JSX but you can actually write code without JSX in Crank by calling createElement directly, or using template string based tools like [htm](https://github.com/developit/htm) or [esx](https://github.com/esxjs/esx). Also, I personally have no say or steering influence on either the [https://facebook.github.io/jsx/](JSX specification), nor any of the transpilers like babel or typescript. If they decide to make JSX more tightly coupled to React, as some proposals are attempting, then we might as a framework have to move beyond JSX, or fork and rename the pattern. Who knows what the future may bring?

If you or others have other naming suggestions, I promise to consider them, but it’ll take a lot to make me want to change the name, given that developers are already saying things like [“isn’t this like crank”](https://twitter.com/kyleshevlin/status/1256793667014025217) whenever developers “spontaneously” come up with the idea that you could write components with generators.

Maybe we can change the name if, for instance, “crank” means penis in Norwegian or something like that.

**Comment by palavrov** [comment]
Well, it was just crazy idea I got on my mind when was trying to promoting Crank to a friend. Crank is good name, I really like it. Didn't resist to share the JS/X idea because think it has values too, and fits with Just JS concept.

Now we have:

> # Crank.js
> Write JSX-driven components with functions, promises and generators.

compare with:

> # JS/X
> JSX generators with JS

Or something like that, which doesn't need more explanations, short and powerful to stuck in mind.

**Comment by brainkim** [comment]
> Well, it was just crazy idea I got on my mind when was trying to promoting Crank to a friend.

I love crazy ideas. Haha what if we called Crank, [`GenX`](https://en.wikipedia.org/wiki/Generation_X)? Again, it’s kinda tough to change the name because it would mean we’d have to change the package names, repository names, and website  urls, but I do appreciate any and all suggestions!

**Comment by palavrov** [comment]
Crank already got momentum so changing its name will harm and confuse. But if you really consider to rename it sooner is better than later. Also x.js.org is already taken ... which is a pity because everything could fit so naturally.

>  Haha what if we called Crank, GenX?

As Generation X-er I like that name, but it shifts the focus too much to non-tech.

**Comment by CyriacBr** [comment]
> Naming is hard and 'crank' is really cool but what about combining JS + JSX in JS/X (or JS!X, JS@X, JS#X, J$X, JS%X, JS^X, JS&X, JS*X, JS+X, JS=X, JS~X, JS|X?

Those names are just going to confuse everyone, and it's not good at all for SEO and troubleshooting *angularjs/angular flashbacks*.
CrankJS is unique and unmistakable.

**Comment by brainkim** [comment]
Closing for housekeeping purposes but feel free to continue the discussion! If you have more name ideas I’m happy to hear them!
