### ISSUE TITLE
root instanceof Node returns false after upgrading from 0.1.6

### ISSUE THREAD

**Issue by calumsult** [bikeshaving/crank#145]
To preface, I think this project is really neat, and I'm probably doing something totally wrong. 👍 

I made a fun test project with 0.1.6 and it worked great. I recently updated it to use current (0.3.1) and doing something as simple as

`renderer.render(<div>hello</div>, document.body);`

errors with root is not a node. I'm using parcel. If I add the crank source directly to the project it works (root instanceof Node now returns true). Either way, if I check root instanceof Node before calling render it always returns true, it's only inside the cjs version in the npm package that it returns false. Any thoughts on what I'm doing wrong?

Thanks for your time!

**Comment by brainkim** [comment]
Hmm, if document.body is not a node, it’s usually null. This happens because the script tag is written in the head. You can fix this by making the script tag async or listening to an event like DOMContentLoaded. This is a good reference for how script tags work (https://eager.io/blog/everything-I-know-about-the-script-tag/).

If this isn’t the problem, lemme know! I’m happy to debug but I’d need a little more in the way of code examples. Thanks for trying Crank!

**Comment by brainkim** [comment]
Fixed by #147 and deployed in 0.3.3
