### ISSUE TITLE
Naming convention for event props of custom crank components (lowercase vs. camelCase)?

### ISSUE THREAD

**Issue by mcjazzyfunky** [bikeshaving/crank#148]
I have not seen a corresponding case in the crank documentation:
Let's assume I want to implement with Crank two custom components `FancyButton` and `DataTable`.
Should I prefer lowercase or camelCase for the event property names?

```jsx
<FancyButton onclick= .../>
<DataTable oncolumheaderclick= .../>
```
or

```jsx
<FancyButton onClick= .../>
<DataTable onColumnHeaderClick= .../>
```

I asked as the convention is clear for React (always camelCase even for normal HTML properties/attributes) but not 100% clear for Crank (while I guess that most Crank developers may prefer camelCase event prop names for custom components).

**Comment by brainkim** [comment]
@mcjazzyfunky Not sure myself TBH. All lower-case is harder to read, but matches the DOM’s event naming conventions (`canplaythrough`, `animationcancel`). Using camelCase on the other hand feels awkward, because the types of events is lowercased `new Event("foo")` but its uppercased in the prop `onFoo`.

I’ve been thinking about extending the behavior of the `this.dispatchEvent` to call any matching props which are functions. In other words, `this.dispatchEvent(new Event("foo"))` would call the `onfoo` prop if it existed and was a function. This further complicates the casing concerns.

> I asked as the convention is clear for React (always camelCase even for normal HTML elements) but not 100% clear for Crank (while I guess that most Crank developers may prefer camelCase event prop names for custom components).

I’ve made it a general rule that we’re not going to be doing casing transforms for anything; for instance, we don’t camelCase SVG props like React does, and we don’t camelCase css styles either. What goes in comes out exactly the same on the DOM side.

I think adhering to the DOM and doing all-lowercase is probably the most future-proof thing to do right now. I think especially using word-boundary delimiters like `-` or `.` isn’t a good idea insofar as you wouldn’t be able to translate it to a JSX prop.

**Comment by mcjazzyfunky** [comment]
Frankly, I think a lot of this naming convention thing is a matter of taste, maybe there's not a "better solution" here.
But I am really strongly of the opinion it's important that there IS an official crank naming convention for that, which should be mentioned in the Crank documentation, otherwise there would be unnecessary trouble.
