### ISSUE TITLE
Generator Function Component Hogs CPU on Safari

### ISSUE THREAD

**Issue by jazzdev** [bikeshaving/crank#150]
Steps to repro:
1. Open Safari on Mac
2. Go to the [Try on CodeSandbox](https://codesandbox.io/s/a-stateful-crank-component-hh8zx) link under A Stateful Component (in the [README.md](https://github.com/bikeshaving/crank/blob/master/README.md))
3. Wait 15 seconds or so 

Observed: the CPU usage on my laptop shoots up and I can hear the fan come on

- Doesn't happen in Chrome
- Doesn't happen on non-Generator examples

**Comment by brainkim** [comment]
I use Safari as my regular browser so this would be troubling if true 😬
Some thoughts:
1. I accidentally did not upgrade the version of Crank used in that example to latest; it was on 0.1.4. I upgraded the template to 0.3.3 but I’m not sure if it’s sticking on the CodeSandbox’s side. I rewrote Crank twice for performance reasons and I encourage everyone to upgrade.
2. The CodeSandbox app might be confounding attempts to understand the performance of Crank.js. Even the minimal app pane seems to use an inordinate amount of resources, maybe because it is compiling on the fly or something https://hh8zx.csb.app. In any case, I would want any performance issues to be reproduced on an otherwise empty HTML page.

I ran the stateful generator example locally in Safari and cannot reproduce the issue.

**Comment by jazzdev** [comment]
Yeah, that makes sense, could be CodeSandbox. I wondered about that, but since it was just generator functions and only Safari, I discounted it. I'll spin up standalone app. I want to do that to learn more about Crank anyway. Great framework!

**Comment by jazzdev** [comment]
Yeah, works fine locally in Safari. Must be something in CodeSandbox. Closing.
