### ISSUE TITLE
Error when aliasing a raw element

### ISSUE THREAD

**Issue by waynebaylor** [bikeshaving/crank#188]
This works as expected:
```javascript
function Greeting({ name = "World" }) {
  return <div>Hello {name}</div>;
}

const Works = Greeting;

renderer.render(<Works/>, document.body);
```

However, the browser gives an error when you do this:
```javascript
const DoesNotWork = <div>Goodbye</div>;

renderer.render(<DoesNotWork/>, document.body);
```
> Unknown tag: [object Object]

CodeSandbox example: https://codesandbox.io/s/gallant-sutherland-f78dl

**Comment by brainkim** [comment]
I think this is expected behavior. The second example should not work because it is using an element as a tag. The correct way to call `renderer.render()` with `DoesNotWork` would be to not wrap it in JSX (`renderer.render(DoesNotWork, document.body)`).

I’m not sure there is a use-case for trying to use an element as an element tag and would be interested to know if any other JSX library/framework has attempted it and for what use case.

**Comment by waynebaylor** [comment]
Doh! Good point. 

I was passing a component as a prop to another component and didn't think to just wrap the prop with `{ }` since it's already a component.
