### ISSUE TITLE
proposal: community

### ISSUE THREAD

**Issue by malcolmstill** [bikeshaving/crank#193]
I was thinking it would be useful to build a community around crank.

To that end I have set up a #crankjs IRC channel on freenode, if anyone would like to join me, and indeed I would be interested in other channels of communication that people would be interested in setting up.

**Comment by brainkim** [comment]
Yes, yes, yes, I get it, I haven’t really been good about fostering a community, and developers are very much pack animals who’d like to move together in terms of adoption. I recently started a new job (at ApolloGraphQL), so I’m pretty unavailable in terms of free time as I ramp up on GraphQL and loading the apollo-client codebase into my head but I do plan on working on this stuff again soon.

This is a lot of words to say, any help on this front is very appreciated! I don’t really use IRC, so this’ll be tough for me, but I did create a subreddit (https://www.reddit.com/r/crankjs/). You’re not going to see me on Twitter because I think it’s a platform optimized for bullying, though I do read things from there. I think that, for now, it makes the most sense to keep community efforts in this repository, in issues and discussions as you see fit.

I have an essay on “reactivity in frameworks” which I’ve been working on for a while now which should generate attention at some point, but really I’m not looking for the same massive wave of people which came when I published the introducing Crank essay. These are mostly people who’d like to criticize design decisions without actually trying things out and seeing how it feels, which is very much integral to a lot of what I did. Anyone and everyone who has installed Crank and tried to build an app with it has my eternal gratitude and attention.

One thing I will say though, is that I’ve heavily documented the actual process of writing [Crank from scratch](https://crank.js.org/blog/writing-crank-from-scratch), so if you’re worried about running into bugs that won’t be fixed, you can just read through the source code and see if it’s something you could understand and fix yourself. It might take a lot of effort, but I promise you that it’s worth it and you’ll come away with a better understanding of frameworks, DOM manipulation, and JavaScript control flow.

Also, here’s the thing. This is my one framework. This is my one shot. I’m not gonna stop maintaining it; I’m not gonna build another one; I am regularly using it in some private cutting edge projects so there’s that. Like I said, if you use Crank to build an app, I am deeply honored that you put your faith in me, and I’m happy to spend as much time helping you out on your journey. So there’s that.

**Comment by ewired** [comment]
I would be in favor of a Discord chat. Lots of JS devs, like the Deno community, are very active on Discord, and many of the surrounding projects have chats there. I have many positive experiences with the Deno-adjacent communities in particular; other places may vary. An IRC bridge is not out of the question for those who prefer IRC, but that would be a bit more infrastructure effort. I understand any hesitance toward using Discord, especially considering the recent Microsoft buyout attempt...

I have plans to integrate Crank with Aleph, the Next-like SSR server for Deno, as they plan to become extendable to other frameworks. I think it'll be good; Crank's straightforward use of standard ES syntax like (async) generators can be compared to Deno's strict following of web standards wherever possible. Both projects share a common 'pure' JS experience.

**Comment by brainkim** [comment]
@ewired The one thing I worry about with realtime chat servers is moderation. I’m one person, and I’m not going to be available 24/7 to monitor these places and enforce the minimum levels of human decency which I would expect for a place I felt responsible for. And while IRC is alright, discord has the additional problem that a lot of people on there are actual children. Not like... adults who weren’t properly socialized and like to throw tantrums, I mean like actual human beings under the age of 18. And I’m not saying kids can’t be good developers or contribute in meaningful ways or whatever, it’s just, it adds a whole new level of headache, right?

For now, I personally feel the most comfortable keeping things to GitHub, but again I’m happy for any help.

**Comment by malcolmstill** [comment]
> I recently started a new job (at ApolloGraphQL),

Congratulations!

> but I did create a subreddit (https://www.reddit.com/r/crankjs/)

Cool, I've joined.

> The one thing I worry about with realtime chat servers is moderation.
> And while IRC is alright

I can absolutely shut the IRC channel down if you have concerns and would rather keep things focussed on github
