### ISSUE TITLE
Typo in website/guides/04-async-components.md

### ISSUE THREAD

**Issue by METACEO** [bikeshaving/crank#30]
Was casually reading the documentation and guides and found this little guy:
 
```javascript
  await p2;
  console.log(document.body.innerHTML); // "Run 2"
  await p3;
  console.log(document.body.innerHTML); // "Run 4"
  await p4;
  console.log(document.body.innerHTML); // "Run 4"
```
Awesome work by the way!.. seeing the JavaScript you have throughout the site is a breath of fresh air!

**Comment by brainkim** [comment]
It might be confusing but that’s actually what you’d see! Because updates 3 and 4 happen while update 2 is pending, what happens is that they’re both enqueued for when the component is ready to rerender again. But because the third update has been made obsolete by the fourth update, it’s simply skipped. However, we couldn’t leave the third update pending forever, however, so we fulfill any update when its next update fulfills. In other words, by the time update 3 fulfills, update 4 has also fulfilled.

It might be confusing, but this made the most sense to me to implement. The docs on how async components are very dense compared to everything else, so if you have any way to make this algorithm a little clearer, I’m very curious to hear your thoughts!

**Comment by METACEO** [comment]
Ahh, ok, I do see what you're describing now and I think the implementation makes sense, too!.. I'll look it over again and see if there's any suggestions I can make!

**Comment by METACEO** [comment]
I'll close this issue but will reference it if I can come up with any suggestions to the documentation to illustrate the implementation!.. thank you and great work, again!
