### ISSUE TITLE
re: "Introducting Crank"

### ISSUE THREAD

**Issue by workingjubilee** [bikeshaving/crank#39]
https://crank.js.org/blog/introducing-crank Typo in page header, should be "Introducing".

A common remark I am seeing on Twitter is about this blog post's incendiary tone. The frustration is warranted and people are sympathetic to it:
- "I appreciate a well-reasoned critique of React"

...but when it bubbles forward as external criticisms, it starts to alienate developers who are not sure about the project:
- "Some of these sentences about other frameworks feel out of place in the docs."
- "I don’t want to try the framework of someone who sees an approach they wouldn’t take and assumes the people behind it don’t have good reasons."

People who are sharing it are also having to apologize for the tone on your behalf:
- "I was not sure about sharing for that reason."
- "I hope it doesn't become the norm."

Now, let us propose I do not care what you do, because I don't. I am not personally invested very much and I am not interested in judging, and I certainly do not think you should defang every sentence you make. But I am aware you have goals, and you may decide that your previous tone has not had the effect you desire, and that it might be worth changing.

So if you are interested in altering your text in order to improve your conveyance of excitement over the thing you made instead of conveying frustration with others, then walking more of this back to ["I-statements"](https://en.wikipedia.org/wiki/I-message) will help. And based on my observation of your position, in general "building pop" for Crank instead of trying to ["build heat"](https://en.wikipedia.org/wiki/Heat_(professional_wrestling)) for your rivals might be the better focus, as your rivals are (friendly, but) already large heels and you do not need to do much but remind people they exist.

I would have sent this privately over e-mail if I had discovered Crank 3 days ago, but you already have quite a bit of attention so people already have their eye on you, here, and you cannot possibly change this post _quietly_ anymore. So by posting here I am not trying to "call you out", nor shame you into a specific course of action, as I am sure there are other routes to take, merely provide a mirror in which to reflect, or, ah, a View to your Model.

**Comment by shirakaba** [comment]
I'm in two minds about this.

On the one hand, looking back at the post I do see what you mean. Indeed, as much of the introduction concerns frustration with React (and arguably takes some shots at it) as it does the actual presentation of a radical and elegant solution. The idea is solid enough that it speaks for itself, and it's right that that could be better focused upon rather than dwelling upon pain points in React.

But on the other hand, for me personally, the introduction struck a strong chord with my own disillusionment with React. Through the frustrated ranting, I could see that we were walking the very same path, facing all the same pain points. It was spellbinding to read all the way to the end to see what solution @brainkim had reached.

As another case study: Svelte was a thing long before Richard Harris started ~drawing parallels to~ calling out React, but when he did, it really got React developers talking. Veteran React developers (myself included) began checking it out, and the top names in the React team were even forced to acknowledge it. Uncouth as it is, being inflammatory does draw attention and provoke conversation whilst being sterile and objective – I would argue – does not.

**Comment by plusgut** [comment]
@workingjubilee I disagree strongly with you. As a framework author myself I tried your approach many times. But if you don't compare your framework and what it does better than others. Than your only response you'll get is "why don't you just use $framework?"

**Comment by workingjubilee** [comment]
The world is analog, so most actual choices in life involve balancing values on gradients. A thermostat has more settings than "Hot" or "Cold", it has a range of degrees. Even choices that _do_ appear binary are not when given the dimension of Time, as becomes the case with many "repeated games". So while any subsample of a sequence may yield a binary value, a sufficiently large step back allows us to witness color, rhythm, and melody. As I spoke in tendencies and uncertainties, not boolean logic, I may answer to assertions I did not cover all possible patterns (true, and if you think these posts are verbose you really don't want me to try that), but I will not answer to claims that I advocated for a single-valued approach when that is, at best, `undefined`.

**Comment by plusgut** [comment]
In my opinion the author of the blogpost was not absolute in any way. But express his frustrations with react, but without being in any way rude to them.
So I see no reason why his language should change.

**Comment by brainkim** [comment]
@workingjubilee
Thanks for catching the typo! Dunno how that happened.

I appreciate the feedback, and I am very good at lurking so I saw the tweets you were referring to. However, I think it’s unfair to say that it’s “a common remark” given that it was maybe 3 people in the same thread, and I know this wasn’t your intent, but I don’t think you should be paraphrasing what people say on Twitter in a GitHub issue, as that feels uhhhhhhh instigative. If these people have a problem they can reach out to me here or by email. Currently, the leaders of tech on Twitter are yelling at each other about a COVID-19 data visualization which has the page weight of a small photo, and bringing tweets to GitHub feels like tracking mud into a place I‘ve deliberately tried to keep somewhat clean.

Ultimately, there is no nice way to say that I think React is heading in the wrong direction, and while people have bristled at the tone of the post, I think there is absolutely no way you could interpret the essay as anything but my personal opinion and I was very careful to provide exact quotations and accurate technical descriptions when I did criticize React.

Again, thank you for these thoughts; it was courageous for you to bring them up, and I will try to mind my tone in the future. I’m closing the issue, because I can think of no good that can come from leaving it open.

**Comment by workingjubilee** [comment]
Of course! I do sincerely respect your decision to stand by your words as you wrote them, and my apologies if I did offer any offense (instigation?).

And thank you! I had not yet noticed the typo was fixed when I made my initial followup remark or I would have closed this myself, as that, after all, was the main reason for the issue.
