### ISSUE TITLE
Virtualized-list components a possible great application?

### ISSUE THREAD

**Issue by cpryland** [bikeshaving/crank#61]
Seems like the libraries like `react-virtualized` could be implemented fairly easily by Crank's async generator components, instead of the hairy machinery involved in those libraries.

Maybe I'm wrong (without implementation (and a deeper understanding of `react-virtualized`) this is just speculation), but my instinct is that if you had a list of 10K entries, that you could have a Crank component that returned essentially just an empty non-zero-height div, and an intersection observer on the parent list that would ask any sub-component element in view or about to come into view to instantiate its actual contents.

Am I off base here?

**Comment by brainkim** [comment]
No I think you’re definitely onto something! One cool thing is that we can actually reuse arrays of elements, because they’re preserved between renders:

```tsx
function *VirtualList() {
  let els = Array.from({length: 1000}, (i) => <VirtualEl crank-key={i} />);
  // some listener which mutates elements
  while (true) {
    yield <div>{els}</div>;
  }
}
```

This might decrease the memory requirements of huge stateful arrays. You could do this in React, but putting actual elements in React state always felt icky, and elements themselves were supposed to be immutable. We don’t have that requirement in Crank, and mutating elements in rare cases where memory needs to be reused could be kinda cool. Maybe it’s a huge mistake but I think there’s a lot of room for experimentation.

**Comment by lishine** [comment]
FYI this is the new kid in the block and the alternative for react-window:
React hooks implementation
https://github.com/tannerlinsley/react-virtual

**Comment by brainkim** [comment]
I’m still trying to figure out virtual lists in 2024. They continue to be tricky to implement and use. I was experimenting with TanStack Virtual for the Crank.js website playground to try and optimize the code editor and wrote some hooks for that (https://github.com/bikeshaving/crank/blob/master/website/src/utils/virtualizer.ts). I ultimately only was able to use it for superficial use-cases because combining rich text editing and virtualization turned out to be very, very difficult.

I still wish there were a virtual list abstraction which didn’t require a priori measurements, and didn’t need you to map over a synthetic data structure or require you to listen for changes. Like ideally, there would be a component which reads its children and selectively renders them without having to have a concept of virtual data like:

```jsx
<Virtual direction="row" scrollElement={parent}>
  {myItems.maps((item) => <Row key={item.key} />}
</Virtual>
```

Having to pass estimates for row/col sizes and margins is finicky, and it all falls apart when it comes to SSR and remembered scroll positions. There’s still a lot of room to innovate I think.

In any case, this is probably best implemented in user-land so I’m closing this issue for housekeeping purposes!
