### ISSUE TITLE
Render priority

### ISSUE THREAD

**Issue by andreabreu-me** [bikeshaving/crank#67]
How does Crank prioritizes renders across components?

Will it be possible to do something like this?

````javascript
import {createElement} from "@bikeshaving/crank";
import {renderer} from "@bikeshaving/crank/dom";

function *Timer() {
  let seconds = 0;
  const interval = setInterval(() => {
    seconds++;
    this.refresh(5); // pass an integer from 0 to 5 to indicate the priority of this refresh
  }, 1000);
  try {
    while (true) {
      yield <div>Seconds: {seconds}</div>;
    }
  } finally {
    clearInterval(interval);
  }
}

renderer.render(<Timer />, document.body);
````

**Comment by brainkim** [comment]
`this.refresh` is a low-level method with no knowledge of schedulers. It runs synchronously if the component renders synchronously and asynchronously otherwise. I’m eager to figure out an API for scheduling stuff, but I think the way to do it would be with a helper higher-order component or something which plugs into a scheduler API. The fact that you can use promises and async generators should also help. In short, I think all the tools are there to build an opt-in concurrent mode on top of Crank. If you have more information on this stuff let me know, and thanks for bringing it up. I definitely would love to see someone work on this with Crank.

**Comment by andreabreu-me** [comment]
Thanks a lot for the explanation. I really hope the success for this library.

**Comment by brainkim** [comment]
Closing for housekeeping purposes.
