### ISSUE TITLE
Reusable component logic with setup and teardown

### ISSUE THREAD

**Issue by wmadden** [bikeshaving/crank#82]
One really common problem with React's imperative style of class components was that it's very difficult to write code that's reused between components and involves both setup and teardown steps without using higher order components.

I can't think of an easy way to achieve this in plain JavaScript generators. How would you go about solving this problem in Crank?

If there's no immediate solution, it might be a good goal to keep in mind as the component API is evolving.

**Comment by monodop** [comment]
I think after thinking about this, one of the hardest things will be dealing with sync vs async code. Consider that you want to implement some form of abstraction (let's just call it a plugin), you'd start with four types of situations that need to be handled:

Component is sync, Plugin is sync
Component is sync, Plugin is async
Component is async, Plugin is sync
Component is async, Plugin is async

On top of that, you may decide to allow plugins to call other plugins, which could have similar types of possibilities.

What this means is: What if my plugin setup logic needs to happen async, but I want to use it in a sync component? or visa versa? What if I want my setup to run async but provide some kind of loading result so that the component can run synchronously or provide a loading spinner or something? What if I need to respond to changes to props async before the component gets them? Or do something after the component rendered? And does the order of these actions matter when there's multiple plugins registered at once? And so on.

We should probably be really careful in designing the api so that we don't create situations where a user has to make concessions about their components to fit whatever third party plugin they're using. But at the same time we need the user to have some kind of control over what's going on without the whole thing being really confusing and having plugins work different ways depending on if you need sync or async. Ideally it should Just Work™. I'm not sure if we'll ever hit that goal if we need to support both sync and async components out of the box, but it is an interesting problem to think about.

**Comment by ryhinchey** [comment]
@wmadden what do you mean by setup and teardown?  Are you thinking of `componentDidMount` and `componentWillUnmount`?

As @monodop pointed out, there are many permutations of component and plugin types - it gets complicated quickly.

Perhaps we could leverage Crank's event system?  This idea isn't fully thought through but it does show how the event system can be used to communicate between both sync/async generators and "utility code" that's used in several components.  

https://codesandbox.io/s/wispy-surf-qbcki?file=/src/index.js

```jsx
/** @jsx createElement */
import { createElement } from "@bikeshaving/crank";
import { renderer } from "@bikeshaving/crank/dom";

const LoadingIndicator = () => <h1>loading</h1>;

// fake user api
const getUser = () =>
  new Promise(resolve => {
    setTimeout(() => {
      resolve({ name: "Jenny" });
    }, 1000);
  });

const getCurrentUser = async ctx => {
  const user = await getUser();
  ctx.dispatchEvent(new CustomEvent("received-user", { detail: { user } }));
  return user;
};

async function* App() {
  let user;

  this.addEventListener("received-user", event => {
    user = event.detail.user;
    this.refresh();
  });

  getCurrentUser(this);

  for await (let _ of this) {
    if (!user) {
      yield <LoadingIndicator />;
    } else {
      yield <h1>{user.name}</h1>;
    }
  }
}

// function* App() {
//   let user;

//   this.addEventListener("received-user", event => {
//     user = event.detail.user;
//     this.refresh();
//   });

//   getCurrentUser(this);

//   for (let _ of this) {
//     if (!user) {
//       yield <LoadingIndicator />;
//     } else {
//       yield <h1>{user.name}</h1>;
//     }
//   }
// }

renderer.render(<App name="true" />, document.body);

```

**Comment by wmadden** [comment]
@brainkim yes I meant something similar to `componentDidMount()`, although the specifics of the mechanism are unimportant. Some way to attach logic to the component lifecycle.

Let me give a concrete example. Let's say you want to respond to changes in something external (a data store, a JS library you're integrating with, etc) by adding an event listener which will trigger `context.refresh()`. When the component unmounts you need to clean up the event listener.

```ts
function* MyComponent({ dataStore }) {
  dataStore.addEventHandler('change', this.refresh);
  try {
    while (true) {
      yield <div>Hello world</div>;
    }
  } catch {
    dataStore.removeEventListener('change', this.refresh);
  }
}
```

How could you extract the event listener code into something reusable?

```ts
function updateOnChange(context, changingEventTarget) {
  changingEventTarget.addEventListener('change', context.refresh);
  // When do we remove the event listener?
}

function* MyComponent({ dataStore }) {
  updateOnChange(this, dataStore);

  while (true) {
    yield <div>Hello world</div>;
  }
}
```

There needs to be some way to perform an action when the component is unmounting.

E.g. a very simple mechanism would be if the framework dispatched an "unmount" event on the context object.

```ts
function updateOnChange(context, changingEventTarget) {
  changingEventTarget.addEventListener('change', context.refresh);
  context.addEventListener('unmount', () => {
    changingEventTarget.removeEventListener('change', context.refresh);
  });
}
```

React solved this problem with hooks, as we know. What's the idiomatic Crank way to describe logic in terms of component lifecycle events?

**Comment by ryhinchey** [comment]
@wmadden agree about an unmount event and think crank could provide most if not all the lifecycle events we need through the internal event system.

I have a branch locally with that unmount working (it was discussed in another issue).  I’ll try to submit a pr soon

**Comment by brainkim** [comment]
There are new context methods for plugins, `schedule` and `cleanup` methods for responding to renders/unmounts, and you can additionally access the current props/rendered values of objects via the `props` and `value` computed properties. I documented four possible ways to reuse logic in [this guide](https://crank.js.org/guides/reusable-logic#strategies-for-reusing-logic).
